@url = http://localhost:3000

### Server healthcheck
GET {{url}}/healthcheck


### Create a new client
POST {{url}}/clientes/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Buzz",
  "apellido": "Lightyear",
  "direccion": "123 Main St",
  "activo": true,
  "telefonos": {
    "codigo_area": "011",
    "nro_telefono": "12345678",
    "tipo": "cel"
  }
}

### Update a client by nro_cliente
PUT {{url}}/clientes/1
Content-Type: application/json
Accept: application/json


{
  "nombre": "Woody",
  "apellido": "Cowboy",
  "direccion": "123 Main St",
  "activo": true,
  "telefonos": [
    {
    "codigo_area": "011",
    "nro_telefono": "12345678",
    "tipo": "cel"
    },
    {
      "codigo_area": "011",
      "nro_telefono": "42424659",
      "tipo": "tel"
    }
  ]
}

### Delete a client by nro_cliente
DELETE {{url}}/clientes/10
Content-Type: application/json
Accept: application/json

### Get client by nro_cliente
GET {{url}}/clientes/11
Content-Type: application/json
Accept: application/json



### Post product
POST {{url}}/productos/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Salsa de tomate",
  "marca": "Ipsum",
  "descripcion": "Original Italiana",
  "precio": 250.49,
  "stock": 200
}

### Post product
POST {{url}}/productos/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Salsa Pizza",
  "marca": "Ipsum",
  "descripcion": "Lista para usar",
  "precio": 300.49,
  "stock": 100
}

### Post product
POST {{url}}/productos/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Salsa Pesto",
  "marca": "Ipsum",
  "descripcion": "Lista para usar",
  "precio": 300.49,
  "stock": 100
}

### Post product
POST {{url}}/productos/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Salsa Pesto",
  "marca": "Marolio",
  "descripcion": "Lista para usar",
  "precio": 350.20,
  "stock": 200
}

### Get products
GET {{url}}/productos/
Content-Type: application/json
Accept: application/json

### Update a product by codigo_producto
PUT {{url}}/productos/1000
Content-Type: application/json
Accept: application/json

{
  "nombre": "arroz premium",
  "marca": "marolio",
  "descripcion": "arroz largo fino",
  "precio": 209.99,
  "stock": 50
}

### Delete a product by codigo_producto
DELETE {{url}}/productos/1000
Content-Type: application/json
Accept: application/json


### Get stock for a product
GET {{url}}/productos/2/stock
Content-Type: application/json
Accept: application/json

### Update stock
PUT {{url}}/productos/2/stock
Content-Type: application/json
Accept: application/json

{
  "change": 50
}

### Set stock level
POST {{url}}/productos/4/stock
Content-Type: application/json
Accept: application/json

{
  "stock": 100
}

### Create factura
POST localhost:3000/facturas/
Content-Type: application/json
Accept: application/json

{
  "nro_cliente": 1,
  "fecha": "2024-11-15",
  "iva": 0.21,
  "items": [
    {
      "codigo_producto": 2,
      "cantidad": 2
    }
  ]
}

### Get facturas by brand
GET {{url}}/facturas/query/9
Content-Type: application/json
Accept: application/json


### Get facturas by brand
GET {{url}}/facturas?marca=Marolio
Content-Type: application/json
Accept: application/json

### Get facturas
GET {{url}}/facturas/
Content-Type: application/json
Accept: application/json

### Get clientes + total expense
GET {{url}}/clientes/query/10
Content-Type: application/json
Accept: application/json

### Get products sold at least once
GET {{url}}/productos/query/8
Content-Type: application/json
Accept: application/json

### Get facturas sorted by date
GET {{url}}/facturas?orden=asc
Content-Type: application/json
Accept: application/json
