@url = http://localhost:3000

### Query 1: Obtener los datos de los clientes junto con sus telefonos
GET {{url}}/clientes/query/1
Content-Type: application/json
Accept: application/json

### Query 2: Obtener el/los teléfono/s y el número de cliente
### del cliente con nombre “Jacob” y apellido “Cooper”
GET {{url}}/clientes/query/2
Content-Type: application/json
Accept: application/json

### Query 3: Mostrar cada teléfono junto con los datos del cliente.
GET {{url}}/clientes/query/3
Content-Type: application/json
Accept: application/json

### Query 4: Obtener todos los clientes que tengan registrada al menos una factura.
GET {{url}}/clientes/query/4
Content-Type: application/json
Accept: application/json

### Query 5: Identificar todos los clientes que no tengan registrada ninguna factura.
GET {{url}}/clientes/query/5
Content-Type: application/json
Accept: application/json

### Query 6: Devolver todos los clientes, con la cantidad de facturas que tienen registradas
### (si no tienen considerar cantidad en 0)
GET {{url}}/clientes/query/6
Content-Type: application/json
Accept: application/json

### Query 7: Listar los datos de todas las facturas que hayan sido compradas
### por el cliente de nombre "Kai" y apellido "Bullock".
GET {{url}}/clientes/query/7
Content-Type: application/json
Accept: application/json

### Query 8: Seleccionar los productos que han sido facturados al menos 1 vez.
GET {{url}}/productos/query/8
Content-Type: application/json
Accept: application/json

### Query 9: Listar los datos de todas las facturas que contengan productos de las marcas “Ipsum”
GET {{url}}/facturas/query/9
Content-Type: application/json
Accept: application/json

### Query 10: Mostrar nombre y apellido de cada cliente junto con lo que gastó en total, con IVA incluido.
GET {{url}}/clientes/query/10
Content-Type: application/json
Accept: application/json