@url = http://localhost:3000

### Server healthcheck
GET {{url}}/healthcheck


### Create a new client
POST {{url}}/clientes/
Content-Type: application/json
Accept: application/json

{
  "nombre": "Buzz",
  "apellido": "Lightyear",
  "direccion": "123 Main St",
  "activo": true,
  "telefonos": {
    "codigo_area": "011",
    "nro_telefono": "12345678",
    "tipo": "cel"
  }
}

### Update a client by nro_cliente
PUT {{url}}/clientes/1
Content-Type: application/json
Accept: application/json


{
  "nombre": "Woody",
  "apellido": "Cowboy",
  "direccion": "123 Main St",
  "activo": true,
  "telefonos": [
    {
    "codigo_area": "011",
    "nro_telefono": "12345678",
    "tipo": "cel"
    },
    {
      "codigo_area": "011",
      "nro_telefono": "42424659",
      "tipo": "tel"
    }
  ]
}

### Delete a client by nro_cliente
DELETE {{url}}/clientes/10
Content-Type: application/json
Accept: application/json

### Get client by nro_cliente
GET {{url}}/clientes/11
Content-Type: application/json
Accept: application/json



### Post product
POST {{url}}/productos/
Content-Type: application/json
Accept: application/json

{
  "codigo_producto": 2000,
  "nombre": "fideos",
  "marca": "marolio",
  "descripcion": "tipo guiseros",
  "precio": 249.99,
  "stock": 20
}

### Get product by codigo_producto
GET {{url}}/productos/1000
Content-Type: application/json
Accept: application/json

### Update a product by codigo_producto
PUT {{url}}/productos/1000
Content-Type: application/json
Accept: application/json

{
  "nombre": "arroz premium",
  "marca": "marolio",
  "descripcion": "arroz largo fino",
  "precio": 209.99,
  "stock": 50
}

### Delete a product by codigo_producto
DELETE {{url}}/productos/1000
Content-Type: application/json
Accept: application/json


### Get stock for a product
GET {{url}}/productos/4/stock
Content-Type: application/json
Accept: application/json

### Update stock
PUT {{url}}/productos/4/stock
Content-Type: application/json
Accept: application/json

{
  "change": -50
}

### Set stock level
POST {{url}}/productos/4/stock
Content-Type: application/json
Accept: application/json

{
  "stock": 100
}